name: Fawesk
author: LimeGlass
description: A Skript addon dedicated to hooking into FAWE
version: 1.0.0-ALPHA
main: me.limeglass.fawesk.Fawesk
loadAfter: [WorldEdit]
depend: [Skript, FastAsyncWorldEdit]