messages:
  command:
    aliases-exists: "<red>The aliases <alias> is already in use."
    aliases-not-exists: "<red>The aliases <alias> does not exist."
    aliases-set: "<green>Aliases <alias> set to <block>"
    aliases-removed: "<green>Aliases <alias> removed."
    aliases-list-entry: "<gray><alias> -> <block>"
    aliases-help: "<yellow>/worldeditaliases set <alias> <block> - Set an alias for a block\n" +
      "/worldeditaliases remove <alias> - Remove an alias\n" +
      "/worldeditaliases list - List all aliases"
